import { Router } from 'express';
import { authenticate } from '../../middleware/auth.middleware';
import * as c from './planner.controller';
const router = Router();
router.use(authenticate);
router.get('/today', c.todayTasks);
router.get('/', c.list);
router.post('/', c.create);
router.post('/bulk-next-day', c.bulkMoveToNextDay);
router.patch('/:id', c.update);
router.patch('/:id/next-day', c.moveToNextDay);
router.delete('/:id', c.remove);
export default router;
